1. NumPy stands for Numerical Python.
2. This library used for working with arrays, linear algebra, fourier transform and matrices.
3. Created by Travis Oliphant in 2005.
4. Works 50 times faster than traditional lists in python as Python list is "array of pointers" and Numpy Array is array of homogenously packed data type.
5. Written mostly in C.
6. source code - https://github.com/numpy/numpy


### Array

In [3]:
import numpy 

arr = numpy.array([1, 2, 3, 4, 5])           # or arr = np.array([1, 2, 3, 4, 5]) 

print(arr)

[1 2 3 4 5]


In [2]:
import numpy as np

In [5]:
print(np.__version__)

1.16.5


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr = np.array(42)                          #0- D Array or scalar
arr1 = np.array([1, 2, 3, 4, 5])            #1- D Array or uni dimensional (has 0-D array as element)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])     #2- D Array / Matrix / 2nd order tensor (has 1- D array as elements)
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])          #3-D Array / 3rd order tensor (has 2D array as element)

In [8]:
print(arr3.ndim)

3


In [10]:
print(arr3.shape)                             #shape of array (here shape is array consists of 2 arrays with 2 array as elements and then 3 elements in each array)     

(2, 2, 3)


In [11]:
arr = np.array([1, 2, 3, 4], ndmin=5)       #creating n-dimensional array (here, keeping n=5)
print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [12]:
print(arr1[0])                               #Accessing 1-D array

1


In [13]:
print(arr1[2] + arr1[3])                    #Scalar Arithmetics in 1-D

7


In [14]:
print('2nd element on 1st dim: ', arr2[0, 1])       #Accessing 2-D array

2nd element on 1st dim:  2


In [15]:
print(arr3[0, 1, 2])                  #Accessing 3-D array

6


In [16]:
print('Last element from 2nd dim: ', arr2[1, -1])        #-ve indexing to access elements from last

Last element from 2nd dim:  6


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])                      #INDEX SLICING 
print(arr[1:5])                                            # includes from 1st element to 4th index element    

[2 3 4 5]


In [18]:
print(arr[4:])                                           #includes 4th index element to last

[5 6 7]


In [19]:
print(arr[:4])                                          #includes elements from beginning to 3rd index element

[1 2 3 4]


In [20]:
print(arr[-3:-1])                                       #from the index 3 from the end to index 1 from the end

[5 6]


In [21]:
print(arr[1:5:2])                                      #We can determine steps also for slicing

[2 4]


In [22]:
print(arr[::2])                                         #Returns every alternate element in array

[1 3 5 7]


In [23]:
print(arr2[1, 1:4])                                      #Slicing in 2-D
print(arr2[0:2, 2])
print(arr2[0:2, 1:4])

[5 6]
[3 6]
[[2 3]
 [5 6]]


Datatypes in array: 
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )


In [24]:
arr = np.array([1, 2, 3, 4], dtype='S')               #We can create array with defined datatype

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [25]:
arr = np.array([1, 2, 3, 4], dtype='i4')               # For i, u, f, S and U we can define size as well.

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [26]:
arr = np.array([1.1, 2.1, 3.1])                          #Changing datatype of elements in array

newarr = arr.astype('i')                                # or    newarr = arr.astype('int') 

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [27]:
arr = np.array([1, 0, 3])                                # Changing integer to boolean

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


NUMPY ARRAY COPY AND VIEW
1. Copy Owns the data and it is different to original. Changes are not interactive in original and copy.
2. View does not owns the data. It is the view of original array only. So any changes made in view wll be reflected to original array.


In [28]:
arr = np.array([1, 2, 3, 4, 5])                             #Creating copy and view
x = arr.copy()                                              # No changes in copy when array element changed
y = arr.view()                                              #View changed
arr[0] = 42

print(arr) 
print(x)
print(y)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]


In [30]:
print(x.base)                                             #Check if array owns it's data
print(y.base)                                             # returns None if the array owns the data. So Copy owns and view doesn't.

None
[42  2  3  4  5]


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)                              #reshape of array, this is 1-D to 2-D

print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)                           #1-D to 3-D reshape.
                                                        #if elements can't be divided completely in new shape, it will throw error.
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])               

newarr = arr.reshape(2, 2, -1)                     #Pass -1 as the value, and NumPy will calculate this number for you.                   

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)                            #Flattening array/ convert multidimensional array into a 1D array.

print(newarr)                                       #We can not pass -1 to more than one dimension.

[1 2 3 4 5 6]


1. In numpy , some other functions to reshape array: flatten, ravel
2. In numpy, some functions for rearranging the elements: rot90, flip, fliplr, flipud

In [35]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:                                     #iterating each element of 3-D array
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [36]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])                             # nditer function in numpy to iterate

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


1. We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

2. NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [37]:
arr = np.array([1, 2, 3])                                     

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [38]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])                  #iterating with step size

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [41]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):                             #Enumerated Iteration Using ndenumerate()
    print(idx, x)                                           
#Enumeration means mentioning sequence number of somethings one by one.    

(0,) 1
(1,) 2
(2,) 3


In [42]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))                             #Joining 1-D array

print(arr)

[1 2 3 4 5 6]


In [44]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)                     #Join two 2-D arrays along rows (axis=1)   ,  If axis is not explicitly passed it is taken as 0.
arr3 = np.stack((arr1, arr2), axis=1)                          #Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
                                                       #We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
arr4 = np.hstack((arr1, arr2))                              # Using hstack() to stack along rows.
arr5 = np.vstack((arr1, arr2))                              # Using vstack()  to stack along columns.
arr6 = np.dstack((arr1, arr2))                              #Using dstack() to stack along height, which is the same as depth.
print(arr)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)                                    #Spliting 1-D array in 3 parts
newarr1 = np.array_split(arr, 4)                                   #If the array has less elements than required, it will adjust from the end accordingly.

print(newarr)
print(newarr1)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


1. We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.
2. The return value of the array_split() method is an array containing each of the split as an array.

In [46]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)                                   #Splitting 2-D array

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [48]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)                                  #returns three 2-D arrays.
newarr1 = np.array_split(arr, 3, axis=1)                         #Split the 2-D array into three 2-D arrays along rows.
newarr2 = np.hsplit(arr, 3)                                       #It also Split 2-D array into three 2-D arrays along rows.  
                                                                  #Similarly, we can use dsplit also.
print(newarr)
print(newarr1)
print(newarr2)


[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = x = np.where(arr == 4)                     #Searching for index with given value in array. (In case of multiple indexes, it will give more elements in output)
y = np.where(arr%2 == 0)                       #Find the indexes where the values are even
z = np.where(arr%2 == 1)                       #Find the indexes where the values are odd

print(x)
print(y)
print(z)

(array([3], dtype=int64),)
(array([1, 3, 5, 7], dtype=int64),)
(array([0, 2, 4, 6], dtype=int64),)


In [53]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)                     #searchsorted() performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order
y = np.searchsorted(arr, 7, side='right')       #By default the left most index is returned, but we can give side='right' to return the right most index instead.
z = np.searchsorted(arr, [2, 8, 10])             # for multiple values
print(x)
print(y)
print(z)

1
2
[0 2 4]


In [55]:
#This method returns a copy of the array, leaving the original array unchanged.
arr = np.array([3, 2, 0, 1])                      #Sorting array , We can sort string, boolean type elements also.
arr1 = np.array([True, False, True])

print(np.sort(arr))
print(np.sort(arr1))

[0 1 2 3]
[False  True  True]


In [3]:
arr = np.array([41, 42, 43, 44])                      #Filtering array : Getting some elements out of an existing array and creating a new array out of them is called filtering.

x = [True, False, True, False]                        # In Numpy, we can filter an array using a boolean index list.

newarr = arr[x]

print(newarr)

[41 43]


In [4]:
arr = np.array([41, 42, 43, 44])                        # In numpy, we can directly filter with condition.

filter_arr = arr > 42                                   # Filter elements from array which are greater than 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0                                 #Filter even elements from array 

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [13]:
from numpy import random                                   # import random package

x = random.randint(100)                                    #Generate a random integer from 0 to 100
y = random.rand()                                          #The random module's rand() method returns a random float between 0 and 1
z = random.randint(100, size=(5))                          #Generate a 1-D array containing 5 random integers from 0 to 100
m = random.randint(100, size=(3, 5))                       #Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100
n = random.rand(5)                                         #Generate a 1-D array containing 5 random floats
o = random.rand(3, 5)                                      #Generate a 2-D array with 3 rows, each row containing 5 random numbers
p = random.choice([3, 5, 7, 9])                            #Return one of the values in an array
                                                           #The choice() method takes an array as a parameter and randomly returns one of the values.
q = random.choice([3, 5, 7, 9], size=(3, 5))               #We can add a size parameter to specify the shape of the array
r = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))           #We can add probabilities for elements also
                                                           #The sum of all probability numbers should be 1.
s = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))       
print("x = ", x)
print("y = ", y)
print("z = ", z)
print("m = ", m)
print("n = ", n)
print("o = ", o)
print("p = ", p)
print("q = ", q)
print("r = ", r)
print("s = ", s )

x =  78
y =  0.8476652219394163
z =  [40 86 15 22 67]
m =  [[78 84 29  8  7]
 [28 18 35 33 81]
 [47 19 49 20 65]]
n =  [0.27852394 0.52154524 0.83809798 0.49457298 0.65416513]
o =  [[0.62679925 0.71936422 0.45659131 0.25123365 0.90968833]
 [0.54614411 0.15515547 0.14142419 0.03304421 0.924855  ]
 [0.81441738 0.54328933 0.59769266 0.51645533 0.75058163]]
p =  5
q =  [[3 7 7 3 7]
 [3 9 5 9 9]
 [3 5 7 9 3]]
r =  [3 7 3 5 3 5 7 7 3 7 5 5 7 3 7 7 7 7 7 7 5 5 5 7 7 7 7 5 3 7 5 5 7 5 7 3 5
 7 5 7 3 7 7 5 5 7 7 7 5 7 7 7 7 3 5 7 5 7 7 7 7 7 5 7 7 7 5 5 7 7 7 7 5 7
 7 5 7 7 5 7 7 7 5 5 7 7 7 7 7 7 3 7 5 7 3 7 7 7 7 5]
s =  [[7 7 5 5 5]
 [5 7 7 5 7]
 [7 7 3 5 7]]


1. Shuffle() : Shuffle means changing arrangement of elements in-place. i.e. in the array itself. It makes changes to the original array.
2. Permutation() : Returns a re-arranged array (and leaves the original array un-changed).
3. random.normal() : Returns a Normal Data Distribution. Consist of three parameters - loc ((Mean) where the peak of the bell exists), scale ((Standard Deviation) how flat the graph distribution should be), size (The shape of the returned array)
4. random.binomial() : Binomial Distribution is a Discrete Distribution. It has three parameters:n (number of trials), p(probability of occurence of each trial (e.g. for toss of a coin 0.5 each)), size (The shape of the returned array)
5. random.poisson() : Poisson Distribution is a Discrete Distribution. It has two parameters: lam (rate or known number of occurences e.g. 2 for above problem) , size (The shape of the returned array).
6. random.uniform() : Used to describe probability where every event has equal chances of occuring.It has three parameters: a(lower bound - default 0 .0), b(upper bound - default 1.0), size(The shape of the returned array)
7. random.logistics() : Logistic Distribution is used to describe growth. Used extensively in machine learning in logistic regression, neural networks etc.It has three parameters: loc(mean, where the peak is. Default 0), scale(standard deviation, the flatness of distribution. Default 1), size(The shape of the returned array)
8. random.multinomial() : Multinomial distribution is a generalization of binomial distribution. It describes outcomes of multi-nomial scenarios unlike binomial where scenarios must be only one of two. e.g. Blood type of a population, dice roll outcome. It has three parameters: n(number of possible outcomes (e.g. 6 for dice roll)), pvals(list of probabilties of outcomes (e.g. [1/6, 1/6, 1/6, 1/6, 1/6, 1/6] for dice roll)), size(The shape of the returned array). 
9. random.exponential : Exponential distribution is used for describing time till next event e.g. failure/success etc. It has two parameters: scale(inverse of rate ( see lam in poisson distribution ) defaults to 1.0), size (The shape of the returned array) 
10. random.chisquare() : Chi Square distribution is used as a basis to verify the hypothesis. It has two parameters: df((degree of freedom)), size(The shape of the returned array)
11. random.rayleigh() : Rayleigh distribution is used in signal processing. It has two parameters: scale((standard deviation) decides how flat the distribution will be default 1.0)), size (The shape of the returned array).
12. random.pareto() : A distribution following Pareto's law i.e. 80-20 distribution (20% factors cause 80% outcome). It has two parameter: a(shape parameter), size(The shape of the returned array). 
13. random.zipf() : Zipf distritutions are used to sample data based on zipf's law. It has two parameters: a(distribution parameter), size(The shape of the returned array).

#### Poisson distribution deals with number of occurences of an event in a time period whereas exponential distribution deals with the time between these events.

#### Zipf's Law: In a collection the nth common term is 1/n times of the most common term. E.g. 5th common word in english has occurs nearly 1/5th times as of the most used word.

In [19]:
arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)                                              # Shuffle

print(arr)
print(random.permutation(arr))                                   # Permutation

[2 1 3 5 4]
[5 2 3 4 1]


In [20]:
x = random.normal(loc=1, scale=2, size=(2, 3))                   # Normal Distribution: Generate a random normal distribution of size 2x3 with mean at 1 and standard deviation of 2
y = random.binomial(n=10, p=0.5, size=10)                        # Binomial Distribution: Given 10 trials for coin toss generate 10 data points
z = random.poisson(lam=2, size=10)                               # Poisson Distribution: Generate a random 1x10 distribution for occurence 2.
m = random.uniform(size=(2, 3))                                  # Uniform Distribution: Create a 2x3 uniform distribution sample
n = random.logistic(loc=1, scale=2, size=(2, 3))                 # Logistic Distribution: Draw 2x3 samples from a logistic distribution with mean at 1 and stddev 2.0
o = random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])   # Multinomial Distribution: Draw out a sample for dice roll. 
                                                                  # Multinomial samples will NOT produce a single value! They will produce one value for each pval.
p = random.exponential(scale=2, size=(2, 3))                      # Draw out a sample for exponential distribution with 2.0 scale with 2x3 size
q = random.chisquare(df=2, size=(2, 3))                           # Draw out a sample for chi squared distribution with degree of freedom 2 with size 2x3
r = random.rayleigh(scale=2, size=(2, 3))                         # Draw out a sample for rayleigh distribution with scale of 2 with size 2x3
s = random.pareto(a=2, size=(2, 3))                               # Draw out a sample for pareto distribution with shape of 2 with size 2x3
t = random.zipf(a=2, size=(2, 3))                                 # Draw out a sample for zipf distribution with distribution parameter 2 with size 2x3


print("x = ", x)
print("y = ", y)
print("z = ", z)
print("m = ", m)
print("n = ", n)
print("o = ", o)
print("p = ", p)
print("q = ", q)
print("r = ", r)
print("s = ", s )
print("t = ", t)

x =  [[1.40305074 3.7468743  1.01188728]
 [0.22946951 1.09637549 3.73896379]]
y =  [4 7 5 7 6 4 5 4 2 4]
z =  [2 1 2 2 0 2 0 0 2 2]
m =  [[0.56253528 0.12614142 0.74146625]
 [0.30591257 0.18480722 0.48467748]]
n =  [[-2.84703022 -0.42405385 -0.08716447]
 [ 1.57427073  1.87786235  1.97338181]]
o =  [0 0 2 1 1 2]
p =  [[1.45739252 5.86563433 3.04854419]
 [1.36681672 1.2047432  4.53308453]]
q =  [[ 1.21374849  5.76640821  1.64567574]
 [ 1.88339761 10.26455214  5.2288108 ]]
r =  [[2.71630326 2.75770494 0.95448305]
 [1.60844335 2.35658267 2.18734566]]
s =  [[0.2776108  0.04901473 0.04319761]
 [0.22240693 0.0409616  0.27241901]]
t =  [[ 1  9  1]
 [19  1  1]]


1. Ufuncs : stands for "Universal Functions". They operates on the ndarray object. 
2. ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements. They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation. ufuncs also take additional arguments, like: "where" (boolean array or condition defining where the operations should take place), "dtype"(defining the return type of elements), "out" (output array where the return value should be copied)
3. Vectorization : Converting iterative statements into a vector based operation is called vectorization.

In [4]:
#ADDING ELEMENTS OF TO LISTS 

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []
                                             # Add the Elements of Two Lists. One way of doing it is to iterate over both of the lists and then sum each elements.
for i, j in zip(x, y):                       # Without ufunc, we can use Python's built-in zip() method
    z.append(i + j)
print("z = " , z)

m = np.add(x, y)                              # With ufunc, we can use the add() function 
print("m = ", m)

z =  [5, 7, 9, 11]
m =  [ 5  7  9 11]


In [5]:
#CREATING YOUR OWN UFUNC
#To create you own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.
#The frompyfunc() method takes the following arguments: function - the name of the function, inputs - the number of input arguments (arrays), outputs - the number of output arrays.


def myadd(x, y):
  return x+y
                                             
myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [7]:
#Check the type of a function to check if it is a ufunc or not. A ufunc should return <class 'numpy.ufunc'>.

print(type(np.add))                                             #ufunc
print(type(np.concatenate))                                     #built-in func

<class 'numpy.ufunc'>
<class 'builtin_function_or_method'>


In [9]:
#Simple Arithmetic ufunc

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)
newarr1 = np.subtract(arr1, arr2)
newarr2 = np.multiply(arr1, arr2)
newarr3 = np.divide(arr1, arr2)
newarr4 = np.power(arr1, arr2)
newarr5 = np.mod(arr1, arr2)
newarr6 = np.remainder(arr1, arr2)
newarr7 = np.divmod(arr1, arr2)                           # return both the quotient and the the mod
newarr8 = np.absolute(newarr1)


print("newarr = " ,newarr)
print("newarr1 = " ,newarr1)
print("newarr2 = ",newarr2)
print("newarr3 = ", newarr3)
print("newarr4 = ", newarr4)
print("newarr5 = ", newarr5) 
print("newarr6 = ", newarr6)
print("newarr7 = ", newarr7)
print("newarr8 = ", newarr8)

newarr =  [30 32 34 36 38 40]
newarr1 =  [-10 -10 -10 -10 -10 -10]
newarr2 =  [200 231 264 299 336 375]
newarr3 =  [0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
newarr4 =  [ 1661992960   602408795           0  1487897765  1090519040 -1144744561]
newarr5 =  [10 11 12 13 14 15]
newarr6 =  [10 11 12 13 14 15]
newarr7 =  (array([0, 0, 0, 0, 0, 0], dtype=int32), array([10, 11, 12, 13, 14, 15], dtype=int32))
newarr8 =  [10 10 10 10 10 10]


In [10]:
#ROUNDING DECIMALS

arr = np.trunc([-3.1666, 3.6667])                         #Remove the decimals, and return the float number closest to zero.
arr1 = np.fix([-3.1666, 3.6667])                          #same as truncate. Remove the decimals, and return the float number closest to zero.
arr2 = np.around(3.1666, 2)                               #The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.
arr3 = np.floor([-3.1666, 3.6667])                        #The floor() function rounds off decimal to nearest lower integer.
arr4 = np.ceil([-3.1666, 3.6667])                         #The ceil() function rounds off decimal to nearest upper integer.

print("arr = " , arr)
print("arr1 = " , arr1)
print("arr2 = " , arr2)
print("arr3 = " , arr3)
print("arr4 = " , arr4)


arr =  [-3.  3.]
arr1 =  [-3.  3.]
arr2 =  3.17
arr3 =  [-4.  3.]
arr4 =  [-3.  4.]


In [11]:
#LOGRITHMIC FUNCTIONS

arr = np.arange(1, 10)                                   # The arange(1, 10) function returns an array with integers starting from 1 (included) to 10 (not included).

print(np.log2(arr))                                      # log at the base 2
print(np.log10(arr))                                     # log at the base 10
print(np.log(arr))                                       # log at the base e


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [12]:
# LOG AT ANY BASE 

from math import log                                      #import log package from math library
import numpy as np

nplog = np.frompyfunc(log, 2, 1)                          # create function for log.

print(nplog(100, 15))                                     # call function

1.7005483074552052


In [14]:
# SUMMATION, PRODUCTS, DIFFERENCES
# Addition is done between two arguments whereas summation happens over n elements.
# If you specify axis=1, NumPy will return the summation/ product of each array.
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
  
newarr = np.add(arr1, arr2)                                 # addition of elements of both arrays index by index.
newarr1 = np.sum([arr1, arr2], axis=1)                      # summation of elements of both arrays over 1st axis.
newarr2 = np.cumsum(arr1)                                   # Cummulation sum of an array.

newarr3 = np.prod(arr)                                      # product of the elements in an array.
newarr4 = np.prod([arr1, arr2])                             # product of the elements of two arrays.
newarr5 = np.prod([arr1, arr2], axis=1)                     # product of elements of both arrays over 1st axis.
newarr6 = np.cumprod(arr1)                                  # Cummulative product of an array



print("newarr = " , newarr)
print("newarr1 = " , newarr1)
print("newarr2 = " , newarr2)
print("newarr3 = " , newarr3)
print("newarr4 = " , newarr4)
print("newarr5 = " , newarr5)
print("newarr6 = " , newarr6)

newarr =  [2 4 6]
newarr1 =  [6 6]
newarr2 =  [1 3 6]
newarr3 =  362880
newarr4 =  36
newarr5 =  [6 6]
newarr6 =  [1 2 6]


In [3]:
# DISCRETE DIFFERENCE 
# A discrete difference means subtracting two successive elements.

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)                                         # discrete difference of an array
newarr1 = np.diff(arr, n=2)                                   # Compute discrete difference of an array twice

print(newarr)
print(newarr1)

[  5  10 -20]
[  5 -30]


In [4]:
# LCM and GCD of numbers

num1 = 4
num2 = 6

x = np.lcm(num1, num2)
y = np.gcd(num1, num2)

print(x)
print(y)

12
2


In [5]:
# LCM and GCD of arrays
# The reduce() method will use the ufunc, on each element, and reduce the array by one dimension.

arr = np.array([3, 6, 9])                                  #LCM of given array  

x = np.lcm.reduce(arr)
m = np.gcd.reduce(arr)                                     #GCD of given array

print(x)
print(m)


arr = np.arange(1, 11)                                     #LCM of all of an array where the array contains all integers from 1 to 10

y = np.lcm.reduce(arr) 

print(y)

18
3
2520


In [8]:
#TRIGNOMETRIC FUNCTIONS

m = np.sin(np.pi/2)                                             # sine value of PI/2
print(m)

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])            # sine values for all of the values in arr   
n = np.sin(arr)
print(n)

arr = np.array([90, 180, 270, 360])                             # Convert all of the values in following array arr to radians
n = np.deg2rad(arr)
print(n)

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])            # Convert all of the values in following array arr to degrees
o = np.rad2deg(arr)
print(o)

# NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given
p = np.arcsin(1.0)
print(p)

arr = np.array([1, -1, 0.1])                                     # angle for all of the sine values in the array
q = np.arcsin(arr)
print(q)

#FNDING HYPOTENOUS.
base = 3
perp = 4
h = np.hypot(base, perp)
print(h)


1.0
[1.         0.8660254  0.70710678 0.58778525]
[1.57079633 3.14159265 4.71238898 6.28318531]
[ 90. 180. 270. 360.]
1.5707963267948966
[ 1.57079633 -1.57079633  0.10016742]
5.0


In [9]:
#HYPERBOLIC FUNCTIONS

m = np.sinh(np.pi/2)                                               # sinh value of PI/2
print(m)

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])               # cosh values for all of the values in arr
n = np.cosh(arr)
print(n)

#Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given.
o = np.arcsinh(1.0)                                                # Find the angle of 1.0
print(o)

arr = np.array([0.1, 0.2, 0.5])                                    # Find the angle for all of the tanh values in array
p= np.arctanh(arr)
print(p)

2.3012989023072947
[2.50917848 1.60028686 1.32460909 1.20397209]
0.881373587019543
[0.10033535 0.20273255 0.54930614]


In [12]:
# SET OPERATIONS
# Sets are used for operations involving frequent intersection, union and difference operations.

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])                      # Convert an array with repeated elements to a set. /Give Unique elements
m = np.unique(arr)
print(m)

arr1 = np.array([1, 2, 3, 4])                                       
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)                                     # union of the given two set arrays
newarr1 = np.intersect1d(arr1, arr2, assume_unique=True)            # intersection of given two set arrays
# the intersect1d(), setdiff1d(), setxor1d() method takes an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])
newarr2 = np.setdiff1d(set1, set2, assume_unique=True)              # difference of the set1 from set2
newarr3 = np.setxor1d(set1, set2, assume_unique=True)               # symmetric difference of the set1 and set2 (the values that are NOT present in BOTH sets)

print(newarr)
print(newarr1)
print(newarr2)
print(newarr3)


[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]
